### ISSUE TITLE
Please remove

### ISSUE THREAD

**Issue by mperham** [jorge-d/sidekiq-pro-fake#1]
I appreciate that you are trying to help and thank you for the intent but there is a reason why I haven't done what you are doing here.  It breaks a number of my existing Enterprise customers.  Would you please yank your versions pushed to rubygems?

**Comment by jorge-d** [comment]
Hi @mperham,

The point was exactly to show that freeing the namespace can be dangerous, as discussed in rubygems/rubygems.org#1226.
I've yanked the versions > 0 in order to avoid errors on your client's build.

The company I currently work for uses your pro version of the gem. If someone with bad intent had reserved the gem we could have ended up in a pretty scary situation. 

I hope you don't mind if I keep the name on rubygems for demonstration purpose, at least for a few weeks.

best regards,

**Comment by mperham** [comment]
Thank you.  This is the crux of the problem:

1. If I leave a version on rubygems under this name, my old customers will break.
2. If I yank all versions, rubygems automatically releases the name for anyone to reserve (as you did) after 90 days.  This happened in Feb and now it's happening in May, 90 days later.

**Comment by mperham** [comment]
Could you add me so I can update the fake gem with one I have prepared?

gem owner sidekiq-pro --add mperham@gmail.com

**Comment by evanphx** [comment]
@jorge-d I'd like to assign this gem back to @mperham to manage this issue. We appreciate you bringing it up and I'd like to give Mike the ability to handle control to supporting it.

Are you ok with me (as a Rubygems.org admin) reassigning him as the owner?

**Comment by jorge-d** [comment]
Alright @evanphx , go ahead
